"""
Источник Bloomberg через RapidAPI: новости, аналитика по тикерам, курсы валют.

Слой 1 подпроекта briefing/. Дополняет sources.py (RSS-заголовки + newspaper3k).
RSS остаётся основным fallback-каналом — Bloomberg API может лечь по лимиту
или таймауту, и тогда брифинг молча продолжает на RSS.

API: bb-finance (apidojo) через RapidAPI. Эндпоинты:
  - /news/list?id=phx-*           — новости по категориям
  - /stories/list?id=eurusd&template=CURRENCY — статьи по тикеру
  - /stories/detail?internalID=.. — AI-саммари (массив предложений)
  - /market/auto-complete?query=.. — поиск тикеров
  - /market/get-cross-currencies?id=.. — кросс-курсы (формат уточняется)

Ключ: RAPIDAPI_KEY в .env (x-rapidapi-key).
"""

import json
import os
import urllib.request
import time as _time

from briefing.sources import (_CRYPTO_RE, _FOREX_RE, _VENUE_RE,
                               DISPLAY_TZ, _fmt_display)

# ДВА хоста RapidAPI (один ключ, разные наборы эндпоинтов):
#   bloomberg-finance — /news/list (phx-* категории) + /stories/detail
#   bb-finance        — /stories/list (по тикерам) + /market/*
_BASE_NEWS    = "https://bloomberg-finance.p.rapidapi.com"
_HOST_NEWS    = "bloomberg-finance.p.rapidapi.com"
_BASE_MARKET  = "https://bb-finance.p.rapidapi.com"
_HOST_MARKET  = "bb-finance.p.rapidapi.com"
_API_KEY      = None

# Категории /news/list. Формат phx-* подтверждён на bb-finance.
_NEWS_CATEGORIES = [
    "phx-markets",
    "phx-currencies",
    "phx-economics",
    "phx-latest",
]

# Наши валютные пары — для stories/list и cross-currencies.
_SYMBOLS = ["EUR/USD", "USD/JPY", "AUD/USD", "USD/CAD"]

# Сколько статей брать с категории/тикера.
_PER_SOURCE = 6

# Обрезка текста.
_TEXT_LIMIT = 1000

_HTTP_TIMEOUT = 15

# Кэш auto-complete на один прогон.
_AUTOCOMPLETE_CACHE = {}


def _get_key():
    global _API_KEY
    if _API_KEY is None:
        _API_KEY = os.getenv("RAPIDAPI_KEY", "") or None
    return _API_KEY


def _bloomberg_get(path, params=None, base=None, host=None, timeout=_HTTP_TIMEOUT):
    key = _get_key()
    if not key:
        return None
    base_url = base or _BASE_MARKET
    api_host = host or _HOST_MARKET
    url = base_url + path
    if params:
        qs = "&".join("%s=%s" % (k, urllib.request.quote(str(v)))
                      for k, v in params.items())
        url += "?" + qs
    req = urllib.request.Request(url, headers={
        "x-rapidapi-key":  key,
        "x-rapidapi-host": api_host,
        "User-Agent":      "Mozilla/5.0 (briefing)",
    })
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return json.loads(r.read())
    except Exception:
        return None


def _extract_newslist_stories(data):
    """Извлечь stories из ответа /news/list (может быть {data:{modules:[...]}})."""
    if not isinstance(data, dict):
        return []
    inner = data.get("data") or {}
    modules = inner.get("modules", [])
    stories = []
    for m in modules:
        slist = m.get("stories", [])
        if slist:
            stories.extend(slist)
    return stories


def _extract_story_fields(s, internal_id_from_list=None):
    """Вытащить общие поля из story (news/list или stories/list).

    Args:
        s: Dict story из любого list-эндпоинта.
        internal_id_from_list: Если передан — использовать этот internalID
                               (в news/list он на верхнем уровне, в stories/list
                               — тоже).

    Returns:
        Dict с полями title/summary/link/ts/internal_id.
    """
    iid = internal_id_from_list or s.get("internalID") or s.get("id")
    title = (s.get("title") or "").strip()
    summary = (s.get("summary") or s.get("autoGeneratedSummary") or "").strip()
    ts = s.get("published")
    if not isinstance(ts, (int, float)):
        ts = int(_time.time())
    return {
        "internal_id": iid,
        "title":       title,
        "summary":     summary,
        "link":        s.get("longURL") or s.get("shortURL") or "",
        "ts":          ts,
    }


def _fetch_detail_text(internal_id, base=_BASE_MARKET, host=_HOST_MARKET):
    """Получить aiSummary из /stories/detail.

    Args:
        internal_id: Bloomberg internalID.

    Returns:
        Строка текста (может быть пустой).
    """
    if not internal_id:
        return ""
    detail = _bloomberg_get("/stories/detail", {"internalID": internal_id},
                            base=base, host=host)
    if not detail or not isinstance(detail, dict):
        return ""
    inner = detail.get("data") or detail
    ai_summary = inner.get("aiSummary", [])
    if isinstance(ai_summary, list):
        return " ".join(str(s) for s in ai_summary).strip()
    return ""


# ── новости по категориям ─────────────────────────────────────────────────

def fetch_bloomberg_news():
    """Новости Bloomberg по phx-категориям с AI-саммари.

    Returns:
        Tuple (items, diag). Формат items как в sources.fetch_news().
    """
    key = _get_key()
    if not key:
        return [], [{"source": "bloomberg_api", "raw": 0, "relevant": 0,
                     "ok": False, "error": "нет RAPIDAPI_KEY"}]

    all_items = []
    seen_ids = set()

    for cat_id in _NEWS_CATEGORIES:
        data = _bloomberg_get("/news/list", {"id": cat_id},
                              base=_BASE_NEWS, host=_HOST_NEWS)
        if not data:
            continue
        for s in _extract_newslist_stories(data)[:_PER_SOURCE]:
            fields = _extract_story_fields(s)
            iid = fields["internal_id"]
            if not iid or iid in seen_ids:
                continue
            seen_ids.add(iid)

            text_check = (fields["title"] + " " + fields["summary"]).lower()
            all_items.append({
                "_internal_id": iid,
                "source":       "Bloomberg",
                "title":        fields["title"],
                "summary":      fields["summary"][:400],
                "link":         fields["link"],
                "ts":           fields["ts"],
                "time_display": _fmt_display(fields["ts"]),
                "forex":        bool(_FOREX_RE.search(text_check)),
                "crypto":       bool(_CRYPTO_RE.search(text_check)),
                "venue":        bool(_VENUE_RE.search(text_check)),
            })

    # Фильтр — только релевантные.
    items = [it for it in all_items if it["forex"] or it["crypto"] or it["venue"]]

    # Detail: aiSummary для каждой (news host).
    detail_ok = 0
    for it in items:
        text = _fetch_detail_text(it.get("_internal_id", ""),
                                  base=_BASE_NEWS, host=_HOST_NEWS)
        if text:
            detail_ok += 1
        it["text"] = text if text else it.get("summary", "")

    diag = [{"source": "bloomberg_api", "raw": len(all_items),
             "relevant": len(items), "detail_ok": detail_ok,
             "ok": True, "error": None}]
    return items, diag


# ── аналитика по тикерам ──────────────────────────────────────────────────

def _resolve_currency_id(symbol):
    """Найти Bloomberg-id валютной пары через /market/auto-complete.

    Args:
        symbol: "EUR/USD"

    Returns:
        Строка id (напр. "EURUSD:CUR") или None.
    """
    if symbol in _AUTOCOMPLETE_CACHE:
        return _AUTOCOMPLETE_CACHE[symbol]

    # Пробуем оба варианта: с косой и без.
    for query in (symbol, symbol.replace("/", "")):
        data = _bloomberg_get("/market/auto-complete", {"query": query})
        if not data:
            continue
        quotes = data.get("quote", [])
        for q in quotes:
            if not isinstance(q, dict):
                continue
            q_sym = (q.get("symbol") or "").upper()
            q_ticker = (q.get("ticker") or "").upper()
            search = symbol.replace("/", "").upper()
            if search in q_sym or search in q_ticker:
                cur_id = q.get("id") or q.get("ticker")
                if cur_id:
                    _AUTOCOMPLETE_CACHE[symbol] = cur_id
                    return cur_id
    return None


def fetch_bloomberg_analysis():
    """Аналитические статьи Bloomberg по нашим валютным парам.

    /stories/list?id=eurusd&template=CURRENCY → полные тексты через detail.

    Returns:
        Tuple (items, diag) как sources.fetch_analysis().
    """
    key = _get_key()
    if not key:
        return [], [{"source": "bloomberg_api", "found": 0, "fetched": 0,
                     "ok": False, "error": "нет RAPIDAPI_KEY"}]

    items = []
    found_total = 0
    fetched_total = 0

    for sym in _SYMBOLS:
        cur_id = _resolve_currency_id(sym)
        if not cur_id:
            continue

        data = _bloomberg_get("/stories/list",
                              {"id": cur_id, "template": "CURRENCY"})
        if not data:
            continue

        stories = (data if isinstance(data, list)
                   else data.get("stories", []) if isinstance(data, dict)
                   else [])
        found_total += len(stories)

        for s in stories[:_PER_SOURCE]:
            fields = _extract_story_fields(s)
            iid = fields["internal_id"]
            if not iid:
                continue

            text = _fetch_detail_text(iid, base=_BASE_MARKET, host=_HOST_MARKET)
            if not text or len(text) < 80:
                text = fields["summary"]
                if not text or len(text) < 80:
                    continue

            fetched_total += 1
            items.append({
                "source":       "Bloomberg",
                "title":        fields["title"],
                "text":         text[:_TEXT_LIMIT],
                "url":          fields["link"],
                "ts":           fields["ts"],
                "time_display": _fmt_display(fields["ts"]),
            })

    diag = [{"source": "bloomberg_api", "found": found_total,
             "fetched": fetched_total, "ok": True, "error": None}]
    return items, diag


# ── рыночные данные ───────────────────────────────────────────────────────

def fetch_bloomberg_market_data():
    """Живые курсы валют из Bloomberg.

    /market/auto-complete → id → /market/get-cross-currencies.

    Returns:
        Dict {symbol: {price, change, change_pct, ts}} — может быть пустым.
    """
    key = _get_key()
    if not key:
        return {}

    currency_ids = []
    for sym in _SYMBOLS:
        cur_id = _resolve_currency_id(sym)
        if cur_id:
            currency_ids.append((sym, cur_id))

    if not currency_ids:
        return {}

    # Один запрос для всех id.
    id_param = ",".join(cid for _, cid in currency_ids)
    data = _bloomberg_get("/market/get-cross-currencies", {"id": id_param})
    if not data:
        return {}

    # Формат ответа неизвестен — пробуем несколько вариантов.
    entries = data if isinstance(data, list) else data.get("results", [])
    if isinstance(entries, dict):
        entries = list(entries.values())

    result = {}
    for i, (sym, _cid) in enumerate(currency_ids):
        entry = entries[i] if i < len(entries) else {}
        if not isinstance(entry, dict):
            continue
        result[sym] = {
            "price":      entry.get("price") or entry.get("last") or entry.get("value"),
            "change":     entry.get("change") or entry.get("netChange"),
            "change_pct": entry.get("changePct") or entry.get("percentChange"),
            "ts":         int(_time.time()),
        }

    return result
