"""
Источник Bloomberg через RapidAPI: полные аннотации новостей.

Слой 1 подпроекта briefing/. Дополняет sources.py (RSS-заголовки + newspaper3k).
RSS остаётся основным fallback-каналом — Bloomberg API может лечь по лимиту
или таймауту, и тогда брифинг молча продолжает на RSS.

API: bloomberg-finance (apidojo) через RapidAPI. ТОЛЬКО /news/list —
эндпоинтов market/* и stories/* на этом API нет (проверено 2026-08-04).
В ответе каждая story уже содержит autoGeneratedSummary (полный абзац),
поэтому detail-запрос не нужен.

Ключ: RAPIDAPI_KEY в .env (x-rapidapi-key).

Формат ответа:
  {"data": {"modules": [{"stories": [{internalID, title, autoGeneratedSummary,
    published (unix!), longURL, primaryCategory, secondaryBrands, premium}]}]}}
"""

import json
import os
import urllib.request
import time as _time

from briefing.sources import (_CRYPTO_RE, _FOREX_RE, _VENUE_RE,
                               DISPLAY_TZ, _fmt_display)

# RapidAPI endpoint (apidojo, bloomberg-finance).
_BASE_URL = "https://bloomberg-finance.p.rapidapi.com"
_API_KEY  = None  # лениво читается из .env при первом вызове
_API_HOST = "bloomberg-finance.p.rapidapi.com"

# Категории /news/list с префиксом 'phx-'. Проверено: phx-latest (живой),
# phx-markets (живой). Остальные — по тому же шаблону.
_NEWS_CATEGORIES = [
    "phx-markets",    # рынки — главный для брифинга
    "phx-currencies", # валюты
    "phx-economics",  # макро
    "phx-latest",     # всё подряд (фильтруем keywords)
]

# Сколько статей брать с категории.
_PER_CATEGORY = 8

# Таймаут HTTP-запросов к RapidAPI (сек).
_HTTP_TIMEOUT = 15


def _get_key():
    """Лениво прочитать RAPIDAPI_KEY из окружения.

    Returns:
        Строка ключа или None.
    """
    global _API_KEY
    if _API_KEY is None:
        _API_KEY = os.getenv("RAPIDAPI_KEY", "") or None
    return _API_KEY


def _bloomberg_get(path, params=None, timeout=_HTTP_TIMEOUT):
    """GET-запрос к Bloomberg RapidAPI.

    Args:
        path:    Путь после базы, напр. "/news/list".
        params:  Dict query-параметров.
        timeout: Таймаут в секундах.

    Returns:
        Parsed JSON (dict/list) или None при ошибке.

    Raises:
        Никогда — все ошибки глушатся, вызывающий проверяет на None.
    """
    key = _get_key()
    if not key:
        return None

    url = _BASE_URL + path
    if params:
        qs = "&".join("%s=%s" % (k, urllib.request.quote(str(v)))
                      for k, v in params.items())
        url += "?" + qs

    req = urllib.request.Request(url, headers={
        "x-rapidapi-key":  key,
        "x-rapidapi-host": _API_HOST,
        "User-Agent":      "Mozilla/5.0 (briefing)",
    })
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return json.loads(r.read())
    except Exception:
        return None


def _extract_stories(data):
    """Извлечь плоский список stories из ответа /news/list.

    Ответ имеет структуру:
      {"data": {"modules": [{"stories": [...]}, ...]}}
    где каждый модуль может иметь свои stories (или не иметь).

    Args:
        data: Разобранный JSON ответа /news/list.

    Returns:
        List story-dict (может быть пустым).
    """
    if not isinstance(data, dict):
        return []
    inner = data.get("data") or {}
    modules = inner.get("modules", [])
    stories = []
    for m in modules:
        slist = m.get("stories", [])
        if slist:
            stories.extend(slist)
    return stories


def fetch_bloomberg_news():
    """Новости Bloomberg с AI-саммари из /stories/detail.

    Забирает /news/list для нескольких phx-категорий, фильтрует по
    FOREX_KEYWORDS/CRYPTO_KEYWORDS как RSS. Для релевантных статей —
    /stories/detail → aiSummary (массив из 3-4 предложений, подробнее
    чем autoGeneratedSummary из списка).

    Args:
        None.

    Returns:
        Tuple (items, diag):
          items — список dict {source, title, summary, text, link, ts,
                               time_display, forex, crypto, venue};
          diag  — список dict {source, raw, relevant, detail_ok, ok, error}.
    """
    key = _get_key()
    if not key:
        return [], [{"source": "bloomberg_api", "raw": 0, "relevant": 0,
                     "ok": False, "error": "нет RAPIDAPI_KEY"}]

    all_items = []
    seen_ids = set()

    for cat_id in _NEWS_CATEGORIES:
        data = _bloomberg_get("/news/list", {"id": cat_id})
        if not data:
            continue

        stories = _extract_stories(data)
        for s in stories[:_PER_CATEGORY]:
            iid = s.get("internalID") or s.get("id")
            if not iid or iid in seen_ids:
                continue
            seen_ids.add(iid)

            title = (s.get("title") or "").strip()
            # summary у Bloomberg почти всегда пустой — используем autoGeneratedSummary.
            summary = (s.get("summary") or s.get("autoGeneratedSummary") or "").strip()

            text_check = (title + " " + summary).lower()

            # published — сразу unix timestamp (int), не строка.
            ts = s.get("published")
            if not isinstance(ts, (int, float)):
                ts = int(_time.time())

            all_items.append({
                "_internal_id": iid,
                "source":       "Bloomberg",
                "title":        title,
                "summary":      summary[:400],
                "link":         s.get("longURL") or s.get("shortURL") or "",
                "ts":           ts,
                "time_display": _fmt_display(ts),
                "forex":        bool(_FOREX_RE.search(text_check)),
                "crypto":       bool(_CRYPTO_RE.search(text_check)),
                "venue":        bool(_VENUE_RE.search(text_check)),
            })

    # Фильтр как в RSS: только новости, попавшие хоть в одну категорию.
    # Без этого в промпт уходят мусорные заголовки (wildfire, P&G merger).
    items = [it for it in all_items if it["forex"] or it["crypto"] or it["venue"]]

    # Для релевантных — полный aiSummary через /stories/detail.
    detail_ok = 0
    for it in items:
        detail = _bloomberg_get("/stories/detail",
                                {"internalID": it.get("_internal_id", "")})
        text = ""
        if detail:
            detail_ok += 1
            if isinstance(detail, dict):
                inner = detail.get("data") or detail
                ai_summary = inner.get("aiSummary", [])
                if isinstance(ai_summary, list):
                    text = " ".join(str(s) for s in ai_summary).strip()
                # Если aiSummary пуст — fallback на autoGeneratedSummary из списка
                # уже лежит в it["summary"].
        if text:
            it["text"] = text
        else:
            it["text"] = it.get("summary", "")

    diag = [{"source": "bloomberg_api", "raw": len(all_items),
             "relevant": len(items), "detail_ok": detail_ok,
             "ok": True, "error": None}]
    return items, diag
